<added import user with xml module>
i-64/CodeFury pull request #9
Opened 2020-10-08 12:40 UTC by kunalrasam

2020-10-08 12:58 UTC, i-64 approved these changes

2020-10-09 17:22 UTC, rkdgr8 requested changes, later dismissed

2020-10-09 17:22 UTC, rkdgr8 commented on meetingRooms/src/main/java/com/meetingRooms/controller/userimportserv.java
> +    			Path path = Paths.get("C:\\Users\\kunal\\Documents\\training\\CodeFury\\meetingRooms\\src\\main\\webapp\\DatabaseOfUsers");
Try to use relative path so it works on everyone's machine.

2020-10-09 17:22 UTC, rkdgr8 commented on meetingRooms/src/main/java/com/meetingRooms/controller/userimportserv.java
> +    			File DIR = new File("c:/xmlFiles");
Can we create the directory in our project itself, instead of absolute 'C:/xmlFiles'. Will not work on linux machines.

2020-10-10 11:13 UTC, vonyvaio approved these changes

2020-10-11 14:59 UTC, merged